application:
  app-name: SpringPractice
  nested:
    version: Second
    port: 8080
  jasper:
    folder: /reports/jasper_simple_practice
    server-url: http://localhost:8080/jasperserver
    username: joeuser
    password: joeuser
    prefix: /rest_v2/resources
server:
  port: 8081